server:
  port: 9090
  
spring:
  security:
    oauth2:
      client:
        registration:
          govbr:
            client-id: <client-id>
            client-secret: <client-secret>
            scope: openid, email, profile, govbr_confiabilidades, govbr_empresa
        provider:
          govbr:
            issuer-uri: <issuer-uri>
      resourceserver:
        jwt:
          issuer-uri: <issuer-uri>